version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend/data:/app/data

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8080
    ports:
      - '3000:3000'
    depends_on:
      - backend
